### ISSUE TITLE
Automatic triage and annotation of test manifests in mozilla-central

### ISSUE THREAD

**Issue by ahal** [mozilla-releng/releng-rfcs#37]
When standing up new platforms there are always many failing tests that need to be either fixed or skipped so that the jobs are green in CI. This process involves pushing to try, triaging failures, manually updating manifests and then pushing to try again to verify things are fixed. Often fixed failures expose new failures and the process needs to be repeated several times. This is a lengthy and time consuming process, with moving goal posts.

Ideally new platforms should just blanket skip everything that fails so that we start getting coverage on the tests that *do* pass as quickly as possible. But in practice, triaging initial failures takes a long time.

Instead, the process for enabling new platforms should be:
1. Create ci changes to enable new config
2. Run a tool

This tool would:
1. Push to try on your behalf (scheduling any newly added tasks)
2. Analyze your push using `mozci` to try and figure out which failures are new and which ones are likely existing intermittents
3. Automatically retrigger tasks (using `taskcluster-cli` or possibly adding this ability to `mozci`) if more data is needed
4. Automatically annotate manifests with a minimal `skip-if` expression to cover the smallest number of configurations possible
5. Go back to 1 and repeat until all tasks are green or known intermittents (as a first pass, it could exit at this stage and then users could re-run the tool manually)

Since this would only be used on new platforms, the tool could be fairly aggressive when skipping. It could potentially even just skip *every* failure and not even worry about whether it is intermittent or not.

One problem that has prevented us from doing any kind of automatic manifest annotations, is that `manifestparser` can't round-trip read/write without losing the comments. Ideally I'd love to stop using a custom parser and switch to using a third party parser. However, we have a fair bit of custom syntax that such a parser likely wouldn't support so we'd need to tweak the formats, which means we'd need to either do so manually (ugh) or we'd need to write some script to do it. At that point adding the ability to `manifestparser` to round-trip read/write with comments is likely the easiest approach.

In the further future, I'd love to use TOML for our test manifests but for now I think sticking with manifestparser helps keep the scope smaller.

As for other suites, WPT style manifests already support automatic annotation and reftest style manifests would need to be standardized or we'd also have to implement round trip comments there. I'd propose we ignore reftests at first (as usual).

**Comment by jmaher** [comment]
+1 on automating this.

A few things:
1) it is best practice to always push to try with `--rebuild 5`, this gives you clearer signals as there should be no realistic reference data to compare against for intermittent tests.
2) it is best to do a series of pushes- each time disabling the topmost high frequency failure in each test group- just in case there are side effects causing the other failures in the same test group. (think- if the browser crashes, how will you know what else will fail/crash if you didn't run the tests)
3) many test failures are not related to a specific test case- either leak/crash/timeout on shutdown or startup; these have a different path to figuring out
4) reftests (and crashtest, sjreftest) don't fall into this workflow, nor does gtest, mochitest-webgl, or perf related tests.  This only applies to most mochitest, marionette, and xpcshell.

**Comment by bhearsum** [comment]
This sounds like a great idea. From my naive standpoint, it doesn't sound too difficult either (it looks like largely glueing together existing tools?)

The one question I have is whether or not we having existing policy on what we _should_ do with failing tests on new platforms. Is it already the case that we disable everything that fails, or do we try to fix some of the tests too? I'm mostly trying to figure out if this is proposing any changes to our standard procedures, or truly just automating existing ones.

**Comment by ahal** [comment]
We're never on the hook for fixing, just disable everything that fails. It's just that even that is pretty time consuming sometimes :).

**Comment by MihaiTabara** [comment]
Resurrecting this in the context of yesterday's conversation, would this tool be helping with the issues we've discussed about Fission?

**Comment by jmaher** [comment]
this tool would be helpful.  If we think we could put 3 weeks of work into this and have it work for mochitest/xpcshell/marionette, then I would advocate for doing it as the ROI would be pretty quick.  I don't see us getting out of the business of greening up tests- there are no clear owners for many tests, even if there were- I don't see coordinating the timing of machine pools and 40 engineers to align well and actually upgrade something.  

This toolchain would depend on automatic manifest rewriting and parsing results of test runs- this would be beneficial for many other use cases- so even just writing that as a first step would make great progress.

**Comment by escapewindow** [comment]
Reiterating what I said in channel: if we can automate away large tasks on our plate (or add tools to cross-train other teams, etc), we should prioritize that automation highly. +1 from me.

>  At that point adding the ability to manifestparser to round-trip read/write with comments is likely the easiest approach.

+1, sounds like this is accurate. It's tempting to throw things away and rewrite or refactor completely, but we likely need to work with incremental evolution with the team's current bandwidth.

**Comment by ahal** [comment]
This falls under the purview of the CI & Quality Tools team now.
