### ISSUE TITLE
Sharing Taskgraph logic between projects

### ISSUE THREAD

**Issue by ahal** [mozilla-releng/releng-rfcs#40]
As standalone Taskgraph is used by more and more projects, we start to see similar patterns emerge. Deciding what should be shared, and what shouldn't can be tricky. Currently there are only two options:

1. Duplicate the logic in a project specific "taskgraph" module, e.g [fenix_taskgraph](https://github.com/mozilla-mobile/fenix/tree/main/taskcluster/fenix_taskgraph).
2. Upstream the logic into standalone Taskgraph itself.

Each of these places has their uses, but neither is perfect.

The problem with 1) is that we tend to copy/paste modules all over the place. E.g, the `multi_dep.py` loader which is copied [here](https://github.com/mozilla-mobile/fenix/blob/main/taskcluster/fenix_taskgraph/loader/multi_dep.py), and [here](https://github.com/mozilla-mobile/focus-android/blob/main/taskcluster/focus_android_taskgraph/loader/multi_dep.py), and [here](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/taskcluster/mozillavpn_taskgraph/loader/multi_dep.py), and [here](https://github.com/mozilla-mobile/android-components/blob/main/taskcluster/ac_taskgraph/loader/multi_dep.py) and [here](https://github.com/mozilla/glean/blob/main/taskcluster/glean_taskgraph/loader/multi_dep.py).. (you get the point).

There are two problems with 2). First, the vast array of different use cases out there means that trying to make a single coherent set of transforms that covers all use cases without sacrificing maintainability is nearly impossible. Chances are we'd end up with the same fate as the [Gecko transforms](https://searchfox.org/mozilla-central/source/taskcluster/gecko_taskgraph/transforms). Second, I have an unofficial goal of tying the `taskgraph` module more closely to Taskcluster itself. I want `taskgraph` to provide a generic and recommended way of implementing Decision tasks for Taskcluster. That means removing Mozilla-specific logic from the "core" library, not adding more of it.

Given these downsides to each approach, I believe we need a 3rd option. Some place (or places) we can add Taskgraph related logic when it needs to be shared across multiple projects, yet doesn't quite fit alongside the "core" Taskgraph functionality.

## Possible Solutions

1. Extensions within Standalone Taskgraph

In this solution, we'd still put everything in one big standalone Taskgraph package, but we'd be careful to explicitly delineate what is part of the "core" and what is not. I'm thinking we could take a queue from [Sphinx's extensions module](https://github.com/sphinx-doc/sphinx/tree/5.x/sphinx/ext). E.g, we may create modules like:
```
taskgraph.ext.scriptworker.loader.multi_dep
taskgraph.ext.scriptworker.transforms.signing
taskgraph.ext.mozilla_mobile.transforms.some_common_mobile_thing
```

2. Separate modular packages

Rather than one big Taskgraph package, we could create small modular ones that provide functionality for specific orgs or use cases. For example we might have a `mozilla-releng/scriptworker-taskgraph` package that provides all of the transforms / loaders / workertypes / etc, needed to interop with our various scriptworker-scripts.

If there's a need, we could create e.g, `mozilla-mobile/mobile-taskgraph` as a place to put shared logic across all the mobile repos. E.g, some example modules:
```
scriptworker_taskgraph.loader.loader.multi_dep
scriptworker_taskgraph.transforms.signing
mobile_taskgraph.transforms.some_common_mobile_thing
```

3. Single `mozilla-taskgraph` package

The last approach I can think of is to create a single `mozilla-taskgraph` package that contains all of the Mozilla specific logic needed. E.g:
```
mozilla_taskgraph.loader.multi_dep
mozilla_taskgraph.transforms.scriptworker.signing
mozilla_taskgraph.transforms.mobile.some_common_mobile_thing
```

**Comment by ahal** [comment]
I think any of these three solutions would be a big improvement on the status quo. Personally I'm leaning towards 2) or 3). I don't have a super preference between those two.

**Comment by JohanLorenzo** [comment]
Thanks for writing this up and for thinking it through, @ahal 👍 

For the context, we've had this issue ever since we started porting taskgraph on the mobile projects, in Q3 2019. Back then, we were thinking on option 2. That said, I really like option 3! I hadn't thought of that, but having everything under the same package would help discoverability and factoring. I get the feeling option 2 may lead to duplication between say `scriptworker_taskgraph` and `mobile_taskgraph`.

**Comment by escapewindow** [comment]
I think I'm leaning towards the first (2), which is `Upstream the logic into standalone Taskgraph itself` (but removing any Mozilla-specific things) and keeping on going that route until we see something that's common that we don't want to duplicate. Kind of like taskgraph supplying a default set of parameters, but you're able to extend it. Similar would be making multi_dep loader official, but you bring your own group_by's. (Especially since multi_dep is a superset of single_dep, and single_dep is *super* common in our usage. Adding a single-dep group_by as part of the official taskgraph would definitely be worthwhile.)

The fact that mobile is considering moving to a monorepo should remove a ton of duplication. If we can convince the mozilla-extensions org of this, that would remove even more. I suspect your 3 brainstorms might not be as needed if that happens.

**Comment by JohanLorenzo** [comment]
> IMO this is a sign that multi_dep is ready to be upstreamed. 

I agree. For what it's worth, I made `multi_dep` upstream in my taskgraph fork for Gitlab CI[1].


> The fact that mobile is considering moving to a monorepo should remove a ton of duplication.

Yeah, I didn't know that 24 hours ago. This will definitely make it easier to factorize all mobile-specific duplication. That said, I wouldn't be surprised if another project starts as multi-repos and we have to share logic between them again. Thus, I think upstreaming as many things as we can in standalone Taskgraph is a goal for sure. Although, I believe we need an official way of sharing common logic that doesn't fit into standalone Taksgraph.

[1] https://gitlab.com/jobgraph-dev/jobgraph/-/blob/c778983711a9d2aa3f0f80f878b8dc2856be9480/src/jobgraph/loader/multi_dep.py

**Comment by ahal** [comment]
> IMO this is a sign that multi_dep is ready to be upstreamed

Yeah, maybe `multi_dep` was a bad example to use, I agree with this. It's a good example of a generic feature that can be used for multiple purposes. I mostly included it in my example layouts to illustrate that these packages could contain things other than transforms (loaders, utility files, etc).

> I think I'm leaning towards the first (2), which is Upstream the logic into standalone Taskgraph itself (but removing any Mozilla-specific things) and keeping on going that route until we see something that's common that we don't want to duplicate.

I believe it's important to solve this soon rather than continuing with the status quo for the following reasons:

1. We already have Mozilla specific things that we want to share as any transforms that interface with scriptworker are Mozilla specific. So signing/balrog/beetmover/etc transforms are all examples of things that I'd hesitate to include in "core" Taskgraph yet could get re-used across multiple projects at Mozilla. So in my view it's not theoretical, were at this point now.
2. The lack of a good place to put this stuff is holding us back. Every time we stand up a new project we wish there was a good place to put shared transforms and code. But because there isn't we copy/paste because it's the most expedient option available. Putting in the scaffolding for this type of code now, will pay dividends for every new project we stand up tomorrow.

> The fact that mobile is considering moving to a monorepo should remove a ton of duplication.

This is a good point. Some misc thoughts here:

1. This likely won't happen for awhile.
2. If we can de-dupe this stuff ahead of time, it'll make said consolidation easier. We'd be less involved with the project to merge the repos and wouldn't be under any time pressure while doing it.

**Comment by escapewindow** [comment]
> > IMO this is a sign that multi_dep is ready to be upstreamed
> 
> Yeah, maybe `multi_dep` was a bad example to use, I agree with this.

Glad we agree here 👍 

> I believe it's important to solve this soon rather than continuing with the status quo for the following reasons:
> 
>     1. We already have Mozilla specific things that we want to share as any transforms that interface with scriptworker are Mozilla specific. So signing/balrog/beetmover/etc transforms are all examples of things that I'd hesitate to include in "core" Taskgraph yet could get re-used across multiple projects at Mozilla. So in my view it's not theoretical, were at this point now.
> 
>     2. The lack of a good place to put this stuff is holding us back. Every time we stand up a new project we wish there was a good place to put shared transforms and code. But because there isn't we copy/paste because it's the most expedient option available. Putting in the scaffolding for this type of code now, will pay dividends for every new project we stand up tomorrow.

My fear here is that we'll have to make some sort of urgent fix to unblock a dot release or chemspill, and taskgraph is often part of that. We went from landing a fix directly in gecko, to landing a fix in taskgraph and bumping a revision in non-gecko, to landing a fix in taskgraph, creating a release and pushing to pypi, waiting for that to populate, bumping versions, and landing that in the non-gecko repo. We may need to repeat these steps in a second or even multiple other python module(s) if the fix crosses the taskgraph and something-else-taskgraph modules.

My fear isn't a blanket r-, but rather something we should be planning for: what is the emergency every-minute-counts break-fix pattern if we have multiple taskgraph modules we need to modify and test to apply the fix?

**Comment by ahal** [comment]
For emergencies in Gecko we can patch the vendored taskgraph(s) directly (and ignore the lint task that checks for mismatches), then once emergency is over land to proper locations, release and re-vendor.

For emergencies in places where taskgraph isn't vendored, we can use the [pip vcs url](https://taskcluster-taskgraph.readthedocs.io/en/latest/howto/bootstrap-taskgraph.html#testing-pre-release-versions-of-taskgraph) trick to point at a pre-release branch or pull request. It's worth bearing in mind that releasing is about a ~2min operation, so this approach is probably best reserved for cases where we need to land a temporary quick fix until a better fix can be implemented.

**Comment by ahal** [comment]
Yeah that's fair. It's not too bad in Gecko since all the code is in the same repo. But for mobile you'd have to push a fix to a PR or branch in one or more places, then test it out in another.

**Comment by ahal** [comment]
I'm planning to write this up as a proper RFC soon. Going to go with approach 3, though we can obviously still discuss and change things within the RFC process.
